### ISSUE TITLE
Testing under real drone

### ISSUE THREAD

**Issue by camillo2008** [SvenGronauer/phoenix-drone-simulation#1]
I really want to try this out, with a simple task, with a real crazyflie drone, have you any suggestion on how should i do it?

**Comment by SvenGronauer** [comment]
Dear @camillo2008,

we are still working on the release of our modified `crazyflie-firmware` that incorporates all features from this repo. I will keep you updated! 

Best, Sven

**Comment by camillo2008** [comment]
Great, waiting for updates!

**Comment by YQXie99** [comment]
Hi, is the modified `crazyflie-firmware` available now? 😊

**Comment by SvenGronauer** [comment]
Dear all,
I have pushed the firmware that we used for our experiments here:
https://github.com/SvenGronauer/crazyflie-firmware-phoenix

Best, Sven
