### ISSUE TITLE
PWM & observation frequency

### ISSUE THREAD

**Issue by xubo92** [SvenGronauer/phoenix-drone-simulation#2]
Hi @SvenGronauer 

Thank you a lot for contributing to this repo, it is really useful!

I have a question about how the frequency of PWM and observation (100hz) is determined. Is it a built-in speed of Pybullet, or it would get affected by the computer hardware speed?  I also saw for the env step loop, there is something like time.sleep(0.05), time.sleep(1/60). why do we need time.sleep()? will it change the 100hz frequency?

Look forward to your reply!

Best,
Xubo

**Comment by SvenGronauer** [comment]
Dear @xubo92,

Glad to hear. First of all, I set the simulation time step of PyBullet to 5ms (i.e. 200Hz):
https://github.com/SvenGronauer/phoenix-drone-simulation/blob/b43e8881f8a253b1984f97924d0fcd59311573c2/phoenix_drone_simulation/envs/base.py#L44

The observation time step is a multiple of the physics time step: I used 100Hz for PWM control. The numerical results of the physics simulator are not affected by your hardware but only the computation time.
The time sleep calls (e.g. time.sleep(1/60)) are only used for rendering purposes and has nothing to do with the internal physics computations.

Cheers,
Sven
