### ISSUE TITLE
Understanding the noisy observation computation

### ISSUE THREAD

**Issue by MarWaltz** [SvenGronauer/phoenix-drone-simulation#4]
Hi Sven,

Yet another question appeared. In the reference code below, we differentiate whether we are at 100Hz or 200Hz since the simulator runs at 200Hz while the observation frequency is only 100 Hz. But why is the low-pass filtering of the gyro (line 168) outside the if-else? The comment says that the filter is applied only with 100Hz, but right now, it is always executed.

https://github.com/SvenGronauer/phoenix-drone-simulation/blob/b43e8881f8a253b1984f97924d0fcd59311573c2/phoenix_drone_simulation/envs/circle.py#L139C1-L170C55

Or do I have a misunderstanding here?

Thanks and best wishes,
Martin

**Comment by SvenGronauer** [comment]
Hi Martin,

the time constant of the Filter is set to: 2/sim_freq = 200Hz. The comment seems outdated to me... Sorry for raising this confusion. 

Best, Sven

**Comment by MarWaltz** [comment]
Alright, thanks a lot!
